# Generated by Django 4.1.1 on 2022-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predresults", old_name="petal_length", new_name="position1",
        ),
        migrations.RenameField(
            model_name="predresults", old_name="petal_width", new_name="position2",
        ),
        migrations.RemoveField(model_name="predresults", name="sepal_length",),
        migrations.RemoveField(model_name="predresults", name="sepal_width",),
        migrations.AddField(
            model_name="predresults",
            name="sentence",
            field=models.CharField(default="sentence", max_length=60),
            preserve_default=False,
        ),
    ]
