# Generated by Django 4.1.1 on 2022-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0002_rename_petal_length_predresults_position1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predresults", name="classification", field=models.FloatField(),
        ),
    ]
