# Generated by Django 4.1.1 on 2022-10-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0003_alter_predresults_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predresults",
            name="classification",
            field=models.CharField(max_length=30),
        ),
    ]
