# Generated by Django 4.1.1 on 2022-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0004_alter_predresults_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predresults", name="position1", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="predresults", name="position2", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="predresults",
            name="sentence",
            field=models.CharField(max_length=100),
        ),
    ]
